-- ─────────────────────────────────────────────
-- COUNTRY PROFILES
-- ─────────────────────────────────────────────
insert into public.country_profiles (country, country_code, flag_emoji, languages, major_industries, cultural_notes, historical_notes, procurement_links, youth_programs, women_programs, sme_agencies, startup_notes, diaspora_notes, business_etiquette) values

('Senegal', 'SN', '🇸🇳',
  ARRAY['Wolof','French','Pulaar','Serer'],
  ARRAY['Fishing','Agriculture','Tourism','Mining','Oil & Gas','Digital Services'],
  'Senegal is known for Teranga — the spirit of hospitality and welcome. Culture is communal, relationship-first. Dakar is the creative and cultural capital of Francophone West Africa.',
  'Home to the Wolof Empire, Jolof Kingdom, and Toucouleur Empire. Senegal was a major center of the transatlantic slave trade and later French colonial rule, gaining independence in 1960.',
  ARRAY['https://www.marchespublics.sn/'],
  'Le Fonds de Financement de la Formation Professionnelle et Technique (3FPT) supports youth training. ANPEJ provides employment support for young Senegalese.',
  'La Direction de la Promotion de la Femme offers programs for women entrepreneurs. FONGIP provides microcredit targeted at women.',
  'ADEPME is the main SME development agency in Senegal. FONSIS is the sovereign wealth fund that co-invests with businesses.',
  'Dakar has a growing startup ecosystem with hubs like Jokkolabs, CTIC Dakar, and Ker Thiossane. Meltwater Entrepreneurial School of Technology (MEST) has a presence. French Tech Dakar is active.',
  'Senegal welcomes diaspora investment. PAISD (Programme d''Appui aux Initiatives de Solidarité pour le Développement) channels diaspora remittances into development projects.',
  'Business is relationship-driven. Meetings often begin with personal conversation before business. Respecting elders and seniority is important. French is the language of business and government.'),

('Ghana', 'GH', '🇬🇭',
  ARRAY['English','Twi','Ga','Ewe','Dagbani','Fante'],
  ARRAY['Gold Mining','Cocoa','Oil & Gas','Tourism','Financial Services','Tech'],
  'Ghana is known as the "Gateway to Africa." The Year of Return 2019 made it a hub for African diaspora reconnection. Accra has a vibrant creative economy.',
  'Home of the Ashanti Empire, one of the most powerful pre-colonial states. The Gold Coast was central to British colonial trade. Independence in 1957 under Kwame Nkrumah made it the first sub-Saharan African country to gain independence.',
  ARRAY['https://www.ppa.gov.gh/'],
  'NEIP (National Entrepreneurship and Innovation Programme) provides grants and coaching to youth. Youth Start-Up Fund provides seed grants up to $10,000.',
  'Ghana Enterprises Agency (GEA) supports women-led SMEs. Women''s Development Fund (WDF) provides credit to women entrepreneurs.',
  'Ghana Enterprises Agency (GEA) provides training, mentoring, and finance to SMEs. GIPC facilitates investment into Ghana.',
  'Accra is home to mHub, Impact Hub Accra, Ghana Tech Lab, and MEST Africa. Ghana StartUp Act passed 2023 provides legal protections and benefits for startups.',
  'Ghana DIASPORA Programme connects overseas Ghanaians to investment opportunities. Needs verification for current active programs.',
  'Punctuality is respected but meetings may start late. English is the business language. Building personal trust before business is important. Dress conservatively for formal meetings.'),

('Nigeria', 'NG', '🇳🇬',
  ARRAY['English','Yoruba','Hausa','Igbo','Fulani','Ijaw'],
  ARRAY['Oil & Gas','Agriculture','Financial Services','Entertainment','Tech','Manufacturing'],
  'Nigeria is Africa''s largest economy and most populous country. Lagos is the commercial capital and a global creative powerhouse. Nollywood is the world''s second-largest film industry.',
  'Home of the Yoruba kingdoms, Benin Empire, Hausa-Fulani Caliphate, and Igbo civilizations. Colonial rule under Britain ended in 1960. Nigeria''s Afrobeats, fashion, and culture have global influence.',
  ARRAY['https://www.ppda.gov.ng/'],
  'Tony Elumelu Foundation provides $5,000 non-refundable capital to 1,000 African entrepreneurs annually. Bank of Industry Youth Fund. NYIF (Nigeria Youth Investment Fund) provides loans up to ₦25 million.',
  'Government Enterprise and Empowerment Programme (GEEP) includes MarketMoni, TraderMoni, and FarmerMoni for women. CBN Creative Industry Finance Initiative for women in creative sectors.',
  'SMEDAN (Small and Medium Enterprises Development Agency) is the primary SME body. Bank of Industry provides loans from ₦500,000 for SMEs.',
  'Lagos has one of Africa''s largest startup ecosystems: CcHub, Ventures Platform, Techpoint Hub, and 200+ tech startups. Nigeria StartUp Act 2022 provides tax waivers and funding frameworks.',
  'Nigerians in Diaspora Organisation (NIDO) connects diaspora to home investment. NIDF (Nigerian Infrastructure Development Fund) channels diaspora capital.',
  'Business is relationship and trust-driven. Being direct but respectful is key. English is official. Lagos moves fast — punctuality is increasingly valued in formal business.'),

('Rwanda', 'RW', '🇷🇼',
  ARRAY['Kinyarwanda','French','English','Swahili'],
  ARRAY['Tourism','Agriculture','Financial Services','ICT','Mining','Manufacturing'],
  'Rwanda is known as the "Singapore of Africa" for its governance, cleanliness, and innovation. Kigali is one of Africa''s fastest-growing cities and a conference capital.',
  'Pre-colonial Rwanda was organized around a complex kingdom structure under the Mwami (king). Following independence in 1962 and the 1994 genocide, Rwanda has achieved extraordinary reconstruction and economic growth.',
  ARRAY['https://www.rppa.gov.rw/'],
  'BDF (Business Development Fund) offers loans and guarantees to youth entrepreneurs. Rwanda Youth Employment & Economic Empowerment Program (RYEEP) provides skills and grants.',
  'Women for Women International Rwanda. WDA (Workforce Development Authority) supports women in technical sectors. BDF has dedicated women entrepreneur credit lines.',
  'BDF (Business Development Fund) is Rwanda''s main SME financing body. RDB (Rwanda Development Board) is the one-stop business registration and investment facilitation center.',
  'Kigali has a vibrant tech ecosystem: KLab, Carnegie Mellon University Africa, Rwanda ICT Chamber, and over 100 startups. Rwanda Startup Act provides benefits for registered startups.',
  'Rwanda Diaspora Global Network (RDGN). Rwanda Diaspora Investment Fund channels diaspora capital into real estate, agri, and tech.',
  'Rwanda is exceptionally formal and professional. English is now an official language and dominant in business. Dress code is conservative and professional. Rwanda prohibits plastic bags.'),

('Kenya', 'KE', '🇰🇪',
  ARRAY['Swahili','English','Kikuyu','Luo','Luhya','Kalenjin'],
  ARRAY['Agriculture','Tourism','Financial Services','Tech','Manufacturing','Real Estate'],
  'Kenya is East Africa''s commercial hub. Nairobi is home to more multinational headquarters than any other African city. M-Pesa revolutionized mobile money and made Kenya a global fintech leader.',
  'Kenya was home to the Swahili Coast civilization, Maasai and Kikuyu communities, and British East Africa colonial rule. Independence in 1963 under Jomo Kenyatta.',
  ARRAY['https://tenders.go.ke/'],
  'Ajira Digital Programme provides digital skills and income to youth. Kazi Mtaani programme provides youth employment. Biashara Kenya offers youth business grants.',
  'Women Enterprise Fund (WEF) provides loans from KES 50,000 to women. Uwezo Fund provides women and youth groups with grants. AWAK (Association of Women Accountants of Kenya).',
  'Kenya National Chamber of Commerce and Industry. KCB Lion''s Den is a leading SME accelerator. KEPSA is the Kenya Private Sector Alliance that advocates for business.',
  'Nairobi''s Silicon Savannah hosts iHub, Nairobi Garage, Google for Startups Launchpad Africa, and Africa''s Internet Exchange Point. Over 300 active tech startups.',
  'Kenya Diaspora Alliance. Kenya National Diaspora Policy. POCKE (Partnership for Change in Kenya) channels diaspora investment into productive sectors.',
  'Business is conducted in English and Swahili. Relationships matter but Nairobi is increasingly transactional in startup culture. Punctuality is valued more than in other East African cities.'),

('Morocco', 'MA', '🇲🇦',
  ARRAY['Arabic','Tamazight','French','Darija','Spanish'],
  ARRAY['Tourism','Phosphates','Agriculture','Automotive','Aerospace','Renewable Energy','Finance'],
  'Morocco is the bridge between Africa, the Arab world, and Europe. Casablanca is North Africa''s financial center. Morocco leads Africa in renewable energy with the Noor Solar Complex.',
  'Morocco has one of the world''s oldest continuous monarchies. Berber civilization predates Arab influence. Morocco was never fully colonized, though France and Spain held protectorates. It was the first country to recognize American independence in 1777.',
  ARRAY['https://www.marchespublics.gov.ma/'],
  'Maroc PME provides funding and support for young entrepreneurs. Moukawalati (My Entrepreneurship) program supports youth business creation with loans and coaching.',
  'Centre Féminin de Formation provides women technical training. Women2B incubator supports women entrepreneurs in Morocco. Al Amana microfinance specifically targets women entrepreneurs.',
  'CRI (Centre Régional d''Investissement) handles regional investment and SME support. CGEM (Confédération Générale des Entreprises du Maroc) is the main business federation.',
  'Casablanca Finance City (CFC) is a platform for companies expanding across Africa. Hub Africa, Technopark Casablanca, and Mohammed VI Polytechnic University (UM6P) are innovation anchors.',
  'Moroccan Diaspora Investment Program. MRE (Marocains Résidant à l''Etranger) programs channel diaspora remittances and investment.',
  'Business culture blends French formality with Arab hospitality. French and Arabic are used in business. Relationships are essential. Meetings may include tea ceremonies.'),

('South Africa', 'ZA', '🇿🇦',
  ARRAY['Zulu','Xhosa','Afrikaans','English','Sotho','Tswana','Venda'],
  ARRAY['Mining','Financial Services','Manufacturing','Agriculture','Tourism','Tech','Retail'],
  'South Africa has the most developed economy in Africa and one of the largest stock exchanges on the continent. Cape Town and Johannesburg are world-class cities with deep creative and business cultures.',
  'Home of the Zulu, Xhosa, Sotho, and many other nations. Dutch settler arrival in 1652 led to colonial dispossession. Apartheid ended in 1994. Nelson Mandela''s release and democratic elections shaped the modern state.',
  ARRAY['https://www.etenders.gov.za/'],
  'NYDA (National Youth Development Agency) provides grants, loans, and mentoring to young South Africans under 35. Youth Employment Service (YES) provides paid work experience.',
  'National Empowerment Fund (NEF) provides funding specifically to black women-owned businesses. SEDA (Small Enterprise Development Agency) has women-focused programmes.',
  'SEDA (Small Enterprise Development Agency) and SEFA (Small Enterprise Finance Agency) are the main SME support bodies. IDC (Industrial Development Corporation) finances larger industrial projects.',
  'Cape Town has Silicon Cape and a global design/tech reputation. Johannesburg''s Rosebank and Sandton districts host Africa''s highest concentration of corporate headquarters and VC firms.',
  'South African Diaspora Network (SADN). BEE (Broad-Based Black Economic Empowerment) codes also apply to diaspora returning to invest.',
  'South Africa is the most western-style in business culture. English dominates. Relationships matter but formal contracts are standard. B-BBEE compliance is critical for government contracts.'),

('Côte d''Ivoire', 'CI', '🇨🇮',
  ARRAY['French','Dioula','Baoulé','Bété','Agni'],
  ARRAY['Cocoa','Coffee','Oil & Gas','Financial Services','Construction','Telecoms'],
  'Côte d''Ivoire produces 40% of the world''s cocoa. Abidjan is the economic capital of Francophone West Africa and home to the African Development Bank (AfDB) headquarters.',
  'The region was home to the Kong Empire and Gyaaman Kingdom before French colonization. Independence in 1960 under Félix Houphouët-Boigny. The country experienced political turbulence in the 2000s but has since stabilized and grown rapidly.',
  ARRAY['https://www.marchespublics.ci/'],
  'Agence Emploi Jeunes provides youth employment support. FDFP (Fonds de Développement de la Formation Professionnelle) trains young people for employment.',
  'Réseau des Femmes d''Affaires de Côte d''Ivoire (RFACI) supports women entrepreneurs. PISCCA supports women in civil society.',
  'CEPICI (Centre de Promotion des Investissements en Côte d''Ivoire) is the one-stop investment center. BNI Microfinance provides SME credit.',
  'Abidjan is growing as a tech hub with initiatives from Orange Digital Center, startups like CinetPay, and the AfDB Digital Lab. French tech ecosystem strong.',
  'Needs verification — limited formal diaspora investment programs currently documented.',
  'Business is conducted in French. Relationship-building over meals is important. Meetings may start late. Showing respect for seniority and titles is essential.'),

('Guinea', 'GN', '🇬🇳',
  ARRAY['French','Pular','Mandinka','Susu','Kissi'],
  ARRAY['Bauxite Mining','Agriculture','Hydroelectric Power','Fishing','Trade'],
  'Guinea holds 25% of the world''s bauxite reserves and has vast hydroelectric potential. Conakry is the capital. Guinea is at an economic turning point with major infrastructure investment underway.',
  'Guinea was part of the Mali Empire and Songhai Empire. French colonization ended in 1958 when Guinea was the only French colony to vote no to the French Community under Sékou Touré. Rich in Mandinka and Pular heritage.',
  ARRAY['https://www.marchespublics.gov.gn/'],
  'AGUIPE (Agence Guinéenne pour la Promotion de l''Emploi) supports youth employment. Needs verification for current funding programs.',
  'PACV (Programme d''Appui aux Communautés Villageoises) has components supporting women. Needs verification for current active programs.',
  'APIP-Guinée is the investment promotion agency. FONIJ provides credit and support for youth entrepreneurs.',
  'Startup ecosystem is nascent but growing. Incubators include Conakry Digital Hub and Impact Hub emerging presence. Mining sector creates downstream tech opportunities.',
  'Significant Guinean diaspora in France, USA, and Senegal. Needs verification for diaspora investment channels.',
  'Business is conducted primarily in French. Relationship-first culture. Trust takes time to build. Religious observance (Islam) is important — schedule around prayer times.'),

('Mali', 'ML', '🇲🇱',
  ARRAY['French','Bambara','Fulani','Dogon','Tuareg','Songhay'],
  ARRAY['Gold Mining','Agriculture','Livestock','Cotton','Salt Trade'],
  'Mali was the heart of the Mali Empire and Songhai Empire — two of the world''s greatest medieval civilizations. Timbuktu was a global center of Islamic scholarship and trade.',
  'The Mali Empire (1235–1600) under Mansa Musa was one of the wealthiest empires in history. Timbuktu''s universities held over 700,000 manuscripts. Modern Mali faces significant security challenges but cultural heritage and gold reserves remain significant.',
  ARRAY['https://www.marchespublics.gov.ml/'],
  'APEJ (Agence pour la Promotion de l''Emploi des Jeunes) provides youth employment and entrepreneurship support. Needs verification for current programs given political situation.',
  'Programme de Microfinance du Mali supports women entrepreneurs. Needs verification for current programs.',
  'APIM (Agence pour la Promotion des Investissements au Mali) is the investment promotion body. CCI Mali is the chamber of commerce.',
  'Very nascent startup ecosystem. Bamako has early-stage activity. Political instability since 2020 military coups creates risk — verify any programs carefully.',
  'Significant Malian diaspora in France and West Africa. FOMDIM (Fonds Malien pour le Développement et l''Initiative Migratoire) has historically channeled diaspora funds. Needs verification.',
  'French is the official business language. Bambara widely spoken. Very relationship and trust-driven. Islamic practice is central. Hospitality is paramount — accepting tea is part of relationship-building.');

-- ─────────────────────────────────────────────
-- SAMPLE OPPORTUNITIES
-- ─────────────────────────────────────────────
insert into public.opportunities (title, country, region, type, sectors, eligibility_age_min, eligibility_age_max, eligibility_gender, eligibility_citizenship, eligibility_residence, diaspora_allowed, business_stage_required, amount, currency, deadline, source_url, source_name, verified_status, summary, documents_required, application_steps, notes) values

-- NIGERIA
('Tony Elumelu Foundation Entrepreneurship Programme', 'Nigeria', 'Pan-African', 'grant',
  ARRAY['tech','agriculture','health','finance','creative','food','education','all'],
  18, 35, NULL, ARRAY['All African citizens'], ARRAY['Africa'], true,
  ARRAY['idea','registered','operating'],
  5000, 'USD', '2025-03-31',
  'https://www.tonyelumelufoundation.org/teep',
  'Tony Elumelu Foundation',
  'verified',
  'The Tony Elumelu Foundation Entrepreneurship Programme (TEEP) provides USD $5,000 in non-refundable seed capital, 12 weeks of business training, mentorship from TEF network, and access to a pan-African entrepreneur community. Open to all African entrepreneurs aged 18–35 with a business idea or early-stage business.',
  ARRAY['Business plan or idea pitch','Valid ID (passport or national ID)','Proof of African citizenship','Brief personal and business bio','Bank account details'],
  ARRAY['Register on the TEF portal at www.tonyelumelufoundation.org','Complete the online application form with your business idea','Submit required documents through the portal','Attend online selection interview if shortlisted','Complete 12-week online training program','Receive USD $5,000 seed capital upon completion'],
  'Applications typically open January–March each year. The programme has supported 18,000+ entrepreneurs across 54 African countries since 2015.'),

('Nigeria Youth Investment Fund (NYIF)', 'Nigeria', 'Nigeria', 'loan',
  ARRAY['agriculture','tech','manufacturing','food','education','health','all'],
  18, 35, NULL, ARRAY['Nigerian citizens'], ARRAY['Nigeria'], false,
  ARRAY['idea','registered','operating'],
  25000000, 'NGN', NULL,
  'https://nyif.nmfb.com.ng/',
  'Federal Government of Nigeria / NMFB',
  'verified',
  'The Nigeria Youth Investment Fund provides interest-free loans between ₦250,000 and ₦25 million to Nigerian youth-owned businesses aged 18–35. The fund targets any viable business sector and is managed by the Nigeria Micro-finance Bank (NMFB).',
  ARRAY['Valid Nigerian ID','BVN (Bank Verification Number)','Business plan','CAC registration (for registered businesses)','Guarantor','Bank statements (6 months)'],
  ARRAY['Visit nyif.nmfb.com.ng to apply','Register an account and complete the application form','Upload required documents','Await credit assessment and approval','Sign loan agreement','Receive disbursement to business account'],
  'Interest-free loans. Repayment begins 6 months after disbursement. Verification of current open application window recommended.'),

('CBN Creative Industry Finance Initiative', 'Nigeria', 'Nigeria', 'loan',
  ARRAY['creative','media','music','fashion'],
  18, NULL, NULL, ARRAY['Nigerian citizens'], ARRAY['Nigeria'], false,
  ARRAY['registered','operating'],
  NULL, 'NGN', NULL,
  'https://www.cbn.gov.ng/',
  'Central Bank of Nigeria',
  'needs_review',
  'The CBN Creative Industry Finance Initiative provides single-digit interest rate loans to Nigerian entrepreneurs in the creative and cultural industries including film, music, fashion, and performing arts. Facilitated through participating banks.',
  ARRAY['Valid Nigerian ID','CAC registration','Business plan','Bank account with participating bank','Collateral or guarantor'],
  ARRAY['Contact any participating commercial bank','Request the CBN Creative Industry loan scheme','Submit business plan and required documents','Bank conducts credit assessment','Approval and disbursement'],
  'Verify current activation status with your bank. The scheme has had periods of suspension. Confirm before applying.'),

-- GHANA
('Ghana NEIP Startup Fund', 'Ghana', 'Ghana', 'grant',
  ARRAY['tech','agriculture','manufacturing','food','creative','all'],
  18, 35, NULL, ARRAY['Ghanaian citizens'], ARRAY['Ghana'], false,
  ARRAY['idea','registered'],
  10000, 'USD', NULL,
  'https://neip.gov.gh/',
  'National Entrepreneurship and Innovation Programme (NEIP)',
  'verified',
  'NEIP provides grants up to $10,000 USD, business development services, and incubation support to young Ghanaian entrepreneurs aged 18–35. The programme includes mentorship, training, and access to markets.',
  ARRAY['Ghana Card or valid ID','Business plan','Proof of age','Application form from NEIP portal'],
  ARRAY['Visit neip.gov.gh','Complete the online application','Attend business plan pitch if shortlisted','Receive grant and mentorship support'],
  'NEIP also provides an incubator hub in Accra. Applications open periodically — check website for current round.'),

('Ghana Enterprises Agency (GEA) Enterprise Loan', 'Ghana', 'Ghana', 'loan',
  ARRAY['manufacturing','agriculture','food','retail','all'],
  18, NULL, NULL, ARRAY['Ghanaian citizens'], ARRAY['Ghana'], false,
  ARRAY['registered','operating'],
  NULL, 'GHS', NULL,
  'https://www.gea.gov.gh/',
  'Ghana Enterprises Agency',
  'verified',
  'The Ghana Enterprises Agency provides enterprise development support, credit facilitation, and business advisory services to Ghanaian SMEs. Credit is available through partner financial institutions for viable businesses.',
  ARRAY['Business registration certificate','Business plan','Financial statements','Valid ID','Bank statements'],
  ARRAY['Visit a GEA regional office or www.gea.gov.gh','Attend GEA business advisory session','Prepare and submit business plan','Credit assessment by partner financial institution','Disbursement on approval'],
  'GEA also offers women-specific enterprise programs and rural enterprise development.'),

-- KENYA
('Kenya Women Enterprise Fund (WEF)', 'Kenya', 'Kenya', 'loan',
  ARRAY['retail','agriculture','food','manufacturing','creative','all'],
  18, NULL, 'female', ARRAY['Kenyan citizens'], ARRAY['Kenya'], false,
  ARRAY['idea','registered','operating'],
  500000, 'KES', NULL,
  'https://wef.co.ke/',
  'Women Enterprise Fund',
  'verified',
  'The Women Enterprise Fund provides affordable credit from KES 50,000 to women entrepreneurs in Kenya to start or expand businesses. Loans are accessed through registered women groups or directly through Constituency Women Enterprise Scheme (CWES).',
  ARRAY['National ID','KRA PIN','Business plan or operating evidence','Group membership (for group loans)','Passport photo'],
  ARRAY['Visit your nearest WEF constituency office','Join or form a women business group','Apply as a group through CWES','Attend mandatory financial literacy training','Receive loan disbursement'],
  'Individual loans also available. Interest rates are subsidized. Repayment periods flexible. Has supported 200,000+ women since 2007.'),

('Kenya NYDA Youth Fund', 'Kenya', 'Kenya', 'grant',
  ARRAY['tech','agriculture','creative','manufacturing','food','all'],
  18, 35, NULL, ARRAY['Kenyan citizens'], ARRAY['Kenya'], false,
  ARRAY['idea','registered'],
  NULL, 'KES', NULL,
  'https://youth.go.ke/',
  'State Department for Youth Affairs - Kenya',
  'needs_review',
  'The Youth Employment and Enterprise Development Programme supports young Kenyan entrepreneurs with grants, training, and business development support. Multiple sub-funds target different sectors.',
  ARRAY['National ID','Business plan','Proof of age','Application form'],
  ARRAY['Check current open programs at youth.go.ke','Complete application form','Submit to constituency youth officer','Attend selection panel','Receive support'],
  'Program availability varies by funding cycle. Verify current open windows.'),

('Nairobi Garage / iHub Acceleration Program', 'Kenya', 'Kenya', 'accelerator',
  ARRAY['tech','finance','health','education','logistics'],
  NULL, NULL, NULL, NULL, ARRAY['Kenya','East Africa'], true,
  ARRAY['idea','registered','operating'],
  NULL, 'USD', NULL,
  'https://nairobigarage.com/',
  'Nairobi Garage',
  'verified',
  'Nairobi Garage and iHub provide workspace, mentorship, investor access, and community for tech startups in East Africa. Cohort-based acceleration programs offer funding access, demo days, and partner network connections.',
  ARRAY['Pitch deck','Business model description','Team background','Product demo if available'],
  ARRAY['Apply online at nairobigarage.com','Submit startup profile and pitch deck','Attend selection interview','Complete cohort program','Demo Day to investors'],
  'Ongoing programs throughout the year. Coworking membership gives access to events and network even outside cohorts.'),

-- RWANDA
('BDF Rwanda SME Loan', 'Rwanda', 'Rwanda', 'loan',
  ARRAY['agriculture','manufacturing','tech','tourism','food','all'],
  18, NULL, NULL, ARRAY['Rwandan citizens'], ARRAY['Rwanda'], false,
  ARRAY['registered','operating'],
  NULL, 'RWF', NULL,
  'https://www.bdf.rw/',
  'Business Development Fund (BDF)',
  'verified',
  'The Business Development Fund (BDF) provides credit guarantees and direct loans to Rwandan SMEs that lack sufficient collateral for commercial bank loans. BDF covers up to 75% of the loan risk for partner banks.',
  ARRAY['Business registration (RDB)','Business plan','Financial statements','Tax clearance certificate','Bank statements (6 months)'],
  ARRAY['Register your business with RDB (rdb.rw)','Approach a BDF partner bank','Complete BDF application forms','BDF conducts credit assessment','Guarantee/loan issued','Business receives financing from bank'],
  'BDF also has a specific Women Entrepreneur Credit Line and Youth Entrepreneur Window. Fees are very low.'),

('Kigali Innovation City Startup Support', 'Rwanda', 'Rwanda', 'accelerator',
  ARRAY['tech','health','agriculture','education','finance'],
  NULL, NULL, NULL, NULL, ARRAY['Rwanda','East Africa'], true,
  ARRAY['idea','registered','operating'],
  NULL, 'USD', NULL,
  'https://kic.rw/',
  'Kigali Innovation City',
  'verified',
  'Kigali Innovation City (KIC) is Rwanda''s flagship innovation hub co-located with Carnegie Mellon University Africa, University of Rwanda, and the African Institute for Mathematical Sciences (AIMS). It provides incubation, acceleration, talent access, and investment connections for tech-focused startups.',
  ARRAY['Business plan','Technical product overview','Team bio','Pitch deck'],
  ARRAY['Apply through KIC portal at kic.rw','Attend selection assessment','Join incubation or acceleration cohort','Access mentors, investors, and KIC network'],
  'KIC is a long-term project. Early tenants get preferential rates. Strong focus on science, technology, and data-driven businesses.'),

-- SENEGAL
('FONSIS Co-Investment Programme', 'Senegal', 'Senegal', 'investment',
  ARRAY['agriculture','manufacturing','energy','tourism','tech','health'],
  NULL, NULL, NULL, ARRAY['Senegalese citizens','African citizens'], ARRAY['Senegal','Africa'], true,
  ARRAY['operating','scaling'],
  NULL, 'XOF', NULL,
  'https://www.fonsis.org/',
  'Fonds Souverain d''Investissements Stratégiques (FONSIS)',
  'verified',
  'FONSIS is Senegal''s sovereign wealth fund that co-invests with private sector businesses in strategic sectors. It takes minority equity stakes and provides patient capital to Senegalese and African businesses operating in Senegal.',
  ARRAY['Detailed business plan','Audited financial statements (3 years)','Legal incorporation documents','Market study','Investment proposal'],
  ARRAY['Prepare detailed investment memorandum','Contact FONSIS at www.fonsis.org','Attend initial screening meeting','Submit full investment proposal','Due diligence process','Investment committee decision'],
  'FONSIS focuses on large-scale investments. Minimum investment is typically in the hundreds of millions XOF range. Better suited to scaling businesses.'),

('ADEPME SME Support Programme', 'Senegal', 'Senegal', 'training',
  ARRAY['manufacturing','retail','food','agriculture','all'],
  NULL, NULL, NULL, ARRAY['Senegalese citizens'], ARRAY['Senegal'], false,
  ARRAY['idea','registered','operating'],
  NULL, 'XOF', NULL,
  'https://www.adepme.sn/',
  'Agence de Développement et d''Encadrement des PME (ADEPME)',
  'verified',
  'ADEPME provides free and subsidized business development services to Senegalese SMEs including: business formalization support, management training, market access assistance, and connections to financing programs including FONGIP microcredit.',
  ARRAY['National ID','Business registration or business idea','Contact information'],
  ARRAY['Visit ADEPME regional office or www.adepme.sn','Attend free business diagnostic session','Enroll in relevant training programs','Access financing referral services','Get certified as ADEPME-supported SME'],
  'ADEPME is free for most services. Has offices in Dakar, Saint-Louis, Thiès, Ziguinchor, and other cities.'),

-- MOROCCO
('Maroc PME Support Programme', 'Morocco', 'Morocco', 'fund',
  ARRAY['manufacturing','tech','agriculture','tourism','health','all'],
  NULL, NULL, NULL, ARRAY['Moroccan citizens'], ARRAY['Morocco'], false,
  ARRAY['registered','operating','scaling'],
  NULL, 'MAD', NULL,
  'https://www.marocpme.ma/',
  'Maroc PME',
  'verified',
  'Maroc PME is the national agency supporting Moroccan SMEs with cash grants for investment, productivity improvement, and internationalization. It subsidizes consultant services, equipment purchases, quality certifications, and market entry costs.',
  ARRAY['Business registration','Financial statements','Investment project description','Tax compliance certificate','Bank statements'],
  ARRAY['Register on marocpme.ma portal','Submit your investment or improvement project','MAROC PME evaluates eligibility','Approved projects receive grant co-funding (typically 20–50% of project cost)','Implement project and receive grant upon completion evidence'],
  'Maroc PME grants are co-financing — the business must pay its share first and is reimbursed. Multiple programs exist for different business sizes.'),

('Casablanca Finance City (CFC) Pan-Africa Programme', 'Morocco', 'Morocco', 'training',
  ARRAY['finance','tech','all'],
  NULL, NULL, NULL, NULL, ARRAY['Africa','Global'], true,
  ARRAY['operating','scaling'],
  NULL, 'USD', NULL,
  'https://www.casablancafinancecity.com/',
  'Casablanca Finance City',
  'verified',
  'Casablanca Finance City (CFC) is Africa''s leading international financial center. It offers African businesses preferential tax rates, a platform to expand across Africa from Morocco, and access to a network of 200+ multinational companies, financial institutions, and professional services firms.',
  ARRAY['Company incorporation documents','Business plan for African expansion','Financial statements','CFC application form'],
  ARRAY['Apply for CFC status at casablancafinancecity.com','Attend CFC selection committee','If approved, register entity in Casablanca Finance City','Access CFC community, events, and investor network','Use CFC as African hub for expansion'],
  'CFC status provides preferential corporate tax rates and access to the CFC network. Well suited for businesses looking to expand across multiple African markets.'),

-- SOUTH AFRICA
('National Empowerment Fund (NEF) Women Fund', 'South Africa', 'South Africa', 'fund',
  ARRAY['manufacturing','retail','tourism','agriculture','health','all'],
  NULL, NULL, 'female', ARRAY['South African citizens'], ARRAY['South Africa'], false,
  ARRAY['registered','operating','scaling'],
  NULL, 'ZAR', NULL,
  'https://www.nef.org.za/',
  'National Empowerment Fund',
  'verified',
  'The NEF''s Women Empowerment Fund provides equity, quasi-equity, and loan financing to black women-owned businesses. Funding ranges from R250,000 to R75 million. The fund targets historically disadvantaged women with viable businesses in any sector.',
  ARRAY['South African ID','CIPC company registration','B-BBEE certificate','Business plan','Financial statements (3 years if operating)','Bank statements (6 months)'],
  ARRAY['Visit www.nef.org.za','Complete funding application online','Submit all required documents','NEF conducts due diligence','Investment committee decision (6–12 weeks)','Funding agreement signed','Funds disbursed'],
  'Applicants must be at least 50.1% black women-owned. NEF also offers business development support post-investment.'),

('SEDA Enterprise Development Programme', 'South Africa', 'South Africa', 'training',
  ARRAY['manufacturing','retail','agriculture','food','creative','all'],
  NULL, NULL, NULL, ARRAY['South African citizens'], ARRAY['South Africa'], false,
  ARRAY['idea','registered','operating'],
  NULL, 'ZAR', NULL,
  'https://www.seda.org.za/',
  'Small Enterprise Development Agency (SEDA)',
  'verified',
  'SEDA provides free non-financial business development services to South African small enterprises including: business registration support, business plan development, mentorship, market access, and referrals to SEFA for financing.',
  ARRAY['South African ID','Business description or plan'],
  ARRAY['Visit nearest SEDA office (countrywide branches)','Attend business needs assessment','Enroll in relevant SEDA programs','Get mentorship and business development support','SEDA refers qualifying businesses to SEFA for finance'],
  'SEDA has offices in all 9 South African provinces and over 50 enterprise incubators nationwide. Services are free.'),

-- COTE D'IVOIRE
('Agence Emploi Jeunes Côte d''Ivoire', 'Côte d''Ivoire', 'Côte d''Ivoire', 'training',
  ARRAY['tech','agriculture','manufacturing','retail','all'],
  18, 35, NULL, ARRAY['Ivorian citizens'], ARRAY['Côte d''Ivoire'], false,
  ARRAY['idea','registered'],
  NULL, 'XOF', NULL,
  'https://www.agenceemploijeunes.ci/',
  'Agence Emploi Jeunes',
  'verified',
  'The Agence Emploi Jeunes (AEJ) supports young Ivorians aged 18–35 with job placement, entrepreneurship training, and business creation support. It provides coaching, capacity building, and connections to financing for youth-led businesses.',
  ARRAY['National ID','Proof of age','Curriculum vitae or business idea description'],
  ARRAY['Register on the AEJ platform at agenceemploijeunes.ci','Attend skills assessment','Enroll in entrepreneurship or employment programme','Complete training modules','Access business creation support and financing connections'],
  'AEJ is a government programme. Services are free for eligible youth.'),

-- PAN-AFRICAN
('African Development Bank (AfDB) Youth Entrepreneurship Investment Banks', 'Pan-Africa', 'Pan-African', 'fund',
  ARRAY['agriculture','tech','manufacturing','climate','health','all'],
  18, 35, NULL, ARRAY['All African citizens'], ARRAY['Africa'], true,
  ARRAY['idea','registered','operating','scaling'],
  NULL, 'USD', NULL,
  'https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/youth-entrepreneurship-and-innovation-multi-donor-trust-fund',
  'African Development Bank',
  'verified',
  'The African Development Bank''s Youth Entrepreneurship and Innovation Multi-Donor Trust Fund (YEI-MDTF) supports national and regional programs that provide seed funding, training, and investment to African youth entrepreneurs. It channels funding through national youth investment banks across member countries.',
  ARRAY['Varies by country program — typically: business plan, valid ID, proof of citizenship, bank account'],
  ARRAY['Identify your country''s AfDB-supported national program','Apply through that national program''s platform','Complete required training modules','Submit business plan','Attend selection process','Receive grant or loan through national program'],
  'This is an umbrella fund — actual application is through country-level programs. Check AfDB website for your country''s current program.'),

('Seedstars Africa Ventures Accelerator', 'Pan-Africa', 'Pan-African', 'accelerator',
  ARRAY['tech','finance','health','agriculture','education','logistics'],
  NULL, NULL, NULL, NULL, ARRAY['Africa'], true,
  ARRAY['operating','scaling'],
  500000, 'USD',
  NULL,
  'https://www.seedstars.com/',
  'Seedstars',
  'verified',
  'Seedstars Africa Ventures is a seed-stage fund investing USD $250,000–$500,000 in African tech startups across multiple countries. They run regional competitions and invest in companies with strong local market traction and scalable models.',
  ARRAY['Pitch deck (10–15 slides)','Cap table','Financial model','Team credentials','Product demo or MVP'],
  ARRAY['Apply through Seedstars World competition or direct pitch','Attend regional competition event','Progress to Seedstars Summit if selected','Investment committee review','Term sheet and due diligence','Investment closed'],
  'Seedstars has invested in 20+ African countries. They prefer startups with proven revenue or strong growth metrics.'),

('Google for Startups Africa Accelerator', 'Pan-Africa', 'Pan-African', 'accelerator',
  ARRAY['tech','finance','health','agriculture','education'],
  NULL, NULL, NULL, NULL, ARRAY['Africa'], true,
  ARRAY['operating','scaling'],
  NULL, 'USD', NULL,
  'https://startup.google.com/accelerator/africa/',
  'Google for Startups',
  'verified',
  'Google for Startups Accelerator Africa is a 3-month equity-free program for seed-to-series-A tech startups from Africa. Selected startups receive Google product credits, mentorship from Google engineers and experts, global network access, and connections to investors. No equity taken.',
  ARRAY['Pitch deck','Company information','Team bios','Product overview and traction metrics'],
  ARRAY['Apply online at startup.google.com/accelerator/africa','Complete detailed online application','Video interview if shortlisted','3-month program with Google mentors','Demo Day presentation','Access to Google''s global network'],
  'Equity-free. Applications typically open annually. Highly competitive — strong product traction and diverse teams preferred.');
