-- Migration 004: Rich country data — investment incentives and ecosystem notes

-- SENEGAL
update public.country_profiles
set
  startup_notes = 'Senegal operates under the Plan Sénégal Émergent (PSE 2035), a national development plan with explicit SME and entrepreneurship targets. The Diamniadio Digital Park — a 120,000m² tech city 30km from Dakar opened in 2022 — provides subsidized office space and infrastructure. Business registration is handled by APIX (Agence pour la Promotion des Investissements) and can be completed online in 24-48 hours. Senegal is an OHADA member state, meaning its business law framework is shared across 17 West and Central African countries, making cross-border expansion legally simpler. DER/FJ (Délégation à l''Entrepreneuriat Rapide des Femmes et des Jeunes) provides grants up to XOF 500M for qualifying entrepreneurs. The Code des Investissements provides 5-8 year tax holidays and import duty exemptions for priority sectors. Free Zone status is available for export-focused businesses. Oil and gas revenue started in 2024 from the Sangomar offshore field, creating new procurement and supply chain opportunities in energy sector.',
  diaspora_notes = 'Senegal has a large diaspora (primarily in France, Italy, USA, and Spain) that accounts for significant remittance flows. The government actively courts diaspora investment through APIX. Non-resident Senegalese can register businesses and open bank accounts without being present. French is the official language of business; Wolof is widely spoken and understood as a commercial language. OHADA membership means diaspora from any of 17 member countries can use the same legal framework they know.',
  cultural_notes = 'Business culture in Senegal emphasizes relationship-building (Teranga — the culture of hospitality). Initial meetings are relationship-focused; business comes after trust is established. French is the official language of business. Islamic practices influence working hours during Ramadan. Titles and formal greetings are important. The Mouride brotherhood network (Murid) is a powerful economic and social force, particularly in trade.'
where country = 'Senegal';

-- GHANA
update public.country_profiles
set
  startup_notes = 'Ghana is one of West Africa''s most business-friendly environments. The Ghana Investment Promotion Centre (GIPC) provides tax holidays, import duty exemptions, and investor support. The Ghana Free Zones Board offers tax exemptions for export-focused businesses. AGROBank provides dedicated agricultural financing. The Ghana Investment Summit attracts significant FDI annually. Company registration through the Registrar General''s Department takes 1-3 days and costs approximately GHS 150. Ghana''s proximity to the sea and Tema Port makes it a natural hub for West African trade. The textile and fashion industry benefits from strong global demand for Kente fabric and Ankara prints, particularly from diaspora markets. COCOBOD supports cocoa farmers with guaranteed offtake and inputs. The cocoa sector creates significant value chain opportunities in processing, packaging, and export.',
  diaspora_notes = 'Ghana''s "Year of Return" and subsequent "Beyond the Return" campaigns have made it the most active destination for African diaspora investment and relocation. Non-resident Ghanaians and diaspora of African descent can invest, register businesses, and purchase land. The GIPC has specific diaspora investment programs. Many diaspora entrepreneurs are building fashion, food, and creative businesses targeting both local and export markets. English is the official language of business.',
  cultural_notes = 'Ghana has a strong entrepreneurial culture and a reputation for being one of Africa''s most stable democracies. Business meetings start with relationship-building. English is spoken across business and government. Traditional authority (chiefs) still plays a role in land and community matters. Respect for elders and hierarchy is important in negotiations. The weekend market culture in Accra''s Osu and Makola is central to commercial activity.'
where country = 'Ghana';

-- NIGERIA
update public.country_profiles
set
  startup_notes = 'Nigeria is Africa''s largest economy and most dynamic startup ecosystem. Lagos is consistently ranked as a top 3 African startup hub. Key programs: Tony Elumelu Foundation (TEF) — $5,000 non-refundable to 1,000 African entrepreneurs annually. Nigeria Youth Investment Fund (NYIF) — loans up to ₦25M for youth entrepreneurs. CBN AGSMEIS — agricultural and SME loans up to ₦10M at 5% interest. CBN Creative Industry Finance Initiative — for music, film, fashion, technology. NITDA Startup Programme — technical support and funding for digital businesses. NEXIM Bank — export financing and market development. NAFDAC — product certification required for food, cosmetics, and pharmaceuticals (budget 4-6 months for this). Pioneer Status Incentive — 3-5 year corporate tax holiday for qualifying new businesses. Export Processing Zones offer tax exemptions for export manufacturers. BPP (Bureau of Public Procurement) portal — mandatory for government contract bids. CAC online registration (cac.gov.ng) takes 2-5 days and costs ₦10,000-₦25,000.',
  diaspora_notes = 'Nigeria has one of Africa''s largest and most economically active diaspora populations. NiDCOM (Nigerians in Diaspora Commission) coordinates diaspora investment programs. Diaspora Nigerians can register businesses through CAC as non-residents. The NDF (Nigeria Diaspora Development Fund) is active. Dollar-denominated accounts available for diaspora. BDC (Bureau De Change) regulations affect remittance flows. Lagos real estate and franchise businesses are popular diaspora investment channels.',
  cultural_notes = 'Nigeria''s business culture varies by region: Lagos is fast-paced and transactional; Abuja (government/oil sector) is more formal; Northern Nigeria is more relationship-oriented with Islamic business practices. "Oga" culture (respect for authority) is pervasive. Relationship-building and trust are critical before major deals. English is the official business language. Phone-first communication is the norm. The "Japa" phenomenon (emigration) creates both diaspora capital and local talent gaps.'
where country = 'Nigeria';

-- RWANDA
update public.country_profiles
set
  startup_notes = 'Rwanda is East Africa''s fastest-growing and most reform-friendly business environment. The Rwanda Development Board (RDB) operates a one-stop shop where companies register in as little as 6 hours — free of charge. The Business Development Fund (BDF) provides loan guarantees for SMEs when commercial banks decline. Priority sectors receive up to 7-year corporate tax holidays. Kigali is a clean, safe, and digitally connected city with reliable electricity. Rwanda is positioning itself as a regional hub for financial services, tourism, MICE (Meetings, Incentives, Conferences, and Events), and manufacturing. Special Economic Zones offer additional incentives. The government''s Vision 2050 plan creates significant procurement opportunities in construction, ICT, and services. Kigali Innovation City is under development as a tech and innovation hub.',
  diaspora_notes = 'Rwanda actively courts diaspora investment, particularly from the Rwandan diaspora in Europe, USA, and across Africa. Non-resident Rwandans can register companies remotely through RDB online portal. The government has created diaspora-specific investment vehicles. English, French, and Kinyarwanda are all official languages — making Rwanda accessible to both Francophone and Anglophone diaspora.',
  cultural_notes = 'Rwanda has a strong culture of execution and accountability ("Imihigo" — performance contracts). Business culture is formal and punctual. Corruption is very low by African standards — the government enforces strict anti-corruption rules. Community work (Umuganda) every last Saturday creates a culture of collective development. English replaced French as the primary language of business and education in 2008.'
where country = 'Rwanda';

-- KENYA
update public.country_profiles
set
  startup_notes = 'Kenya is East Africa''s most established startup and investment hub, known globally as "Silicon Savannah." Nairobi''s iHub was Africa''s first major tech hub. Konza Technopolis (Silicon Savannah masterplan) is a $14 billion smart city project south of Nairobi. KCB Bank and Equity Bank both have active SME product suites with competitive rates. Special Economic Zones (SEZs) and Export Processing Zones (EPZs) offer significant incentives for manufacturers and exporters. The Kenya Women Enterprise Fund provides loans and training to women entrepreneurs. Uwezo Fund targets youth and women with affordable capital. AGPO (Access to Government Procurement Opportunities) reserves 30% of government procurement for youth, women, and persons with disabilities — a powerful entry point for new businesses. M-Pesa mobile money infrastructure makes Kenya one of the most financially connected markets in Africa.',
  diaspora_notes = 'Kenya has an active diaspora particularly in the USA, UK, Canada, and Australia. The Kenya Diaspora Alliance facilitates investment and business connections. Kenyans abroad can register businesses and access banking remotely. Nairobi real estate is a popular diaspora investment channel. The Kenya Diaspora Investment Programme (KDIP) offers preferential terms.',
  cultural_notes = 'Kenya''s business culture is entrepreneurial and relatively direct by East African standards. English and Swahili are both official languages. Nairobi is cosmopolitan and fast-paced. Relationship-building matters but business can happen quickly. Tribe and regional identity can influence business networks — awareness of this is useful. Mobile-first everything: M-Pesa is the default payment method for even large transactions.'
where country = 'Kenya';

-- MOROCCO
update public.country_profiles
set
  startup_notes = 'Morocco''s Investment Charter 2022 is the most reform-friendly investment legislation in the country''s modern history, significantly reducing bureaucracy and offering enhanced incentives. Casablanca Technopark provides subsidized office space, co-working facilities, and a network for tech startups. UM6P (Mohammed VI Polytechnic University) in Benguerir has built an innovation ecosystem with incubators, labs, and venture connections. Morocco''s proximity to Europe (14km from Spain across the Strait of Gibraltar) makes it a natural nearshoring hub. The Casablanca Finance City is Africa''s leading financial hub. Morocco has free trade agreements with the EU, USA, and multiple Arab countries. The Tangier Med Port is the largest port in Africa and the Mediterranean. Arabic, French, and increasingly Darija (Moroccan Arabic) are used in business.',
  diaspora_notes = 'Morocco has 5+ million citizens living abroad (Moroccan diaspora known as MRE — Marocains Résidant à l''Étranger), primarily in France, Spain, Italy, and Belgium. MREs send over $10 billion in remittances annually. The government has specific programs for MRE investment including CRI (Regional Investment Centers) with dedicated diaspora desks. MREs can purchase property, invest in businesses, and access mortgages with preferential terms. French is essential for business dealings.',
  cultural_notes = 'Morocco blends Arab, Berber, and French business cultures. Formal greetings and titles are important. Meetings may start late. Ramadan significantly affects business pace. French is the language of business documentation and high-level negotiations. Arabic (Darija) is essential for local market relationships. Building trust through multiple meetings before major decisions is expected. Halal certification matters for food products.'
where country = 'Morocco';

-- SOUTH AFRICA
update public.country_profiles
set
  startup_notes = 'South Africa has the most sophisticated financial system in Africa. B-BBEE (Broad-Based Black Economic Empowerment) codes create significant procurement preference for Black-owned businesses — government and large corporations must source from B-BBEE compliant suppliers, creating a powerful supply chain opportunity. Special Economic Zones (SEZs) offer corporate tax holidays and import duty exemptions. The National Empowerment Fund (NEF) provides loans and equity for Black entrepreneurs, including the NEF Women Fund (up to R1.2M). The Employment Tax Incentive reduces the cost of hiring young employees. SEFA (Small Enterprise Finance Agency) provides SME financing. SEDA (Small Enterprise Development Agency) provides free business support. The Companies and Intellectual Property Commission (CIPC) offers online company registration in 1 business day.',
  diaspora_notes = 'South Africa is a destination country for African diaspora from Zimbabwe, Nigeria, DRC, and across the continent. South African diaspora abroad are primarily in the UK, Australia, New Zealand, and USA. The government has created investment facilitation programs for South Africans abroad. The rand''s volatility creates both risk and opportunity for diaspora investors. English is the dominant language of business.',
  cultural_notes = 'South Africa has 11 official languages and significant cultural diversity. Business culture is heavily influenced by English corporate norms in urban areas. Ubuntu philosophy (collective humanity) influences team culture. B-BBEE is the defining framework for business relationships with government and corporations. The relationship between traditional authority and modern business varies by province. Load-shedding (power outages) is a significant operational reality businesses must plan for.'
where country = 'South Africa';

-- CÔTE D''IVOIRE
update public.country_profiles
set
  startup_notes = 'Côte d''Ivoire is West Africa''s second-largest economy and the world''s largest cocoa producer. CEPICI (Centre de Promotion des Investissements en Côte d''Ivoire) offers a one-stop investment center that can create a company in 48 hours. The Plateforme Industrielle d''Abidjan (PIA) is a 1,400-hectare industrial zone with free zone benefits including tax exemptions and streamlined customs. ANASUR and AGENCE CI provide SME support. The Plan National de Développement (PND 2021-2025) prioritizes agro-industry, manufacturing, and digital economy. French is the official language and business operates entirely in French. The country returned to strong economic growth after political instability and has maintained 7%+ GDP growth in recent years. Abidjan''s port is the busiest in West Africa.',
  diaspora_notes = 'Côte d''Ivoire has a significant diaspora in France and across Francophone Africa. Non-residents can invest and register businesses through CEPICI. The BRVM (Bourse Régionale des Valeurs Mobilières) operates the shared stock exchange for UEMOA countries — accessible to diaspora investors. Cocoa sector value chain offers specific diaspora investment vehicles.',
  cultural_notes = 'Business in Côte d''Ivoire is conducted entirely in French. Relationship-building is essential before business. Hierarchy is respected — always engage decision-makers, not just staff. The business culture blends French corporate norms with West African relationship culture. Abidjan is cosmopolitan and relatively fast-paced for West Africa. Catholic and Muslim holidays both affect business schedules.'
where country = 'Côte d''Ivoire';

-- GUINEA
update public.country_profiles
set
  startup_notes = 'Guinea holds some of the world''s largest bauxite reserves (60% of global supply) and significant gold and iron ore deposits. The mining sector creates substantial downstream and supply chain opportunities for local businesses. ANAIM (Agence Nationale des Aires Marines Protégées) oversees maritime sector development. Oil exploration partnerships are active offshore. AGUIPE and APIP (Agence de Promotion des Investissements Privés) support private investment. The country has significant agricultural potential in rice, coffee, and tropical fruits that remains underdeveloped. Political instability (coup in 2021) is a risk factor that must be accounted for in planning. French is the official language of business.',
  diaspora_notes = 'Guinea has a diaspora in France, USA, Senegal, and other West African countries. The political situation requires diaspora investors to conduct careful due diligence. The mining sector is accessible to diaspora investors with the right connections.',
  cultural_notes = 'Guinea has a strong oral culture — verbal agreements and relationships matter enormously. French is the official language but Pular, Malinke, and Susu are widely spoken. Business culture is relationship-intensive. The Fula (Peul) merchant networks are powerful in trade. Political uncertainty requires patience and relationship investment before significant commitments.'
where country = 'Guinea';

-- MALI
update public.country_profiles
set
  startup_notes = 'Mali has significant gold mining and agricultural sectors. The Zone Franche de Kayes offers investment incentives near the Senegal border. APIM (Agence pour la Promotion des Investissements au Mali) provides investment support. The country is an OHADA member state. IMPORTANT: Mali has experienced significant political instability since 2012, with two coups (2020, 2021) and ongoing security challenges in the north and center of the country. Business investment should be carefully risk-assessed. Bamako remains relatively stable. Agricultural opportunities in cotton, millet, and livestock remain real. French is the official business language.',
  diaspora_notes = 'Mali has one of Africa''s largest diaspora relative to population size, primarily in France, Côte d''Ivoire, Senegal, and Guinea. Remittances are a major part of the economy. Diaspora investment should focus on Bamako and the south where security is more stable.',
  cultural_notes = 'Mali has a rich Mande merchant tradition — the Dyula trading networks have operated across West Africa for centuries. Islam is central to life and business. Respect and patience in relationships is essential. French is the official language; Bambara is the most widely spoken local language. The griots (oral historians and social connectors) remain important in community and business relationships.'
where country = 'Mali';
